In [4]:
import pandas as pd
import pickle
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
import numpy as np
from tensorflow.keras.models import load_model

In [5]:
model = load_model('model.h5')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [26]:
## load the encoder and scaler
with open('One_hot_encoder.pkl','rb') as file:
    ohe_geo=pickle.load(file)

with open('Standard_scaler.pkl', 'rb') as file:
   scaler = pickle.load(file)

with open('Label_encoder.pkl', 'rb') as file:
   le = pickle.load(file)

In [7]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [12]:
input_df = pd.DataFrame([input_data])

In [13]:
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [21]:
geo_encoded = ohe_geo.transform([input_df['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns= ohe_geo.get_feature_names_out())
geo_encoded_df

c:\Users\Ekangsh\OneDrive\Desktop\Projects\Customer Churn ANN\venv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [23]:
input_df.drop('Geography', axis=1, inplace=True)

In [27]:
input_df['Gender'] = le.transform(input_df['Gender'])

In [33]:
input_df = pd.concat([geo_encoded_df,input_df], axis=1)
input_df

,Geography_France,Geography_Germany,Geography_Spain,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,1.0,0.0,0.0,600,1,40,3,60000,2,1,1,50000

In [34]:
input_df

,Geography_France,Geography_Germany,Geography_Spain,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,1.0,0.0,0.0,600,1,40,3,60000,2,1,1,50000

In [37]:
input_scaled = scaler.fit_transform(input_df)

In [39]:
prediction = model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step

array([[0.19772583]], dtype=float32)

In [41]:
prediction_proba = prediction[0][0]
prediction_proba

np.float32(0.19772583)

In [42]:
if prediction_proba > 0.5:
    print('The customer is likely to churn.')
else:
    print('The customer is not likely to churn.')

The customer is not likely to churn.